-- create database db9
-- create table Student_table(stdid int,name varchar(50),class int)
-- insert into Student_table values(101,'Sarang',10)
-- select * from Student_table
-- insert into Student_table(stdid,name,class) values (102,'abu',10),(105,'raju',10)
-- select * from Student_table
-- select stdid,name from Student_table
-- insert into Student_table(stdid,name,class) values (102,'abu',11),(105,'raju',09)
-- select * from Student_table
-- select * from Student_table where class=10
-- select * from Student_table where class>10
-- create table  employee(empid int,Name varchar(20),job varchar(20),salary int)
 -- insert into employee(empid,Name,job,salary) values (102,'abu','librarian',15000),(105,'raju','teacher',25000),(101,'Sarang','doctor',100000)
 select * from employee